# Generated by Django 4.2.10 on 2026-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_rename_accounts_em_user_id_idx_accounts_em_user_id_6989e4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="care_recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
