# Generated by Django 4.2.10 on 2026-04-14 12:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_care_recipient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                validators=[accounts.models.validate_iana_timezone],
            ),
        ),
    ]
