# Generated by Django 4.2.10 on 2026-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_fallback_lifetime_cap",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
