# Generated by Django 4.2.10 on 2026-04-14 06:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BehaviorCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=80)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Behavior categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Behavior",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("whats_happening", models.TextField()),
                ("what_not_to_do", models.JSONField(blank=True, default=list)),
                ("what_to_say", models.JSONField(blank=True, default=list)),
                ("why_it_works", models.TextField()),
                ("common_triggers", models.JSONField(blank=True, default=list)),
                ("bonus_tips", models.JSONField(blank=True, default=list)),
                (
                    "dementia_stage",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("early", "Early"),
                            ("middle", "Middle"),
                            ("late", "Late"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "search_text",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="behaviors",
                        to="knowledgebase.behaviorcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["slug"], name="knowledgeba_slug_e91b0d_idx"),
                    models.Index(
                        fields=["is_published"], name="knowledgeba_is_publ_0740ab_idx"
                    ),
                    models.Index(
                        fields=["dementia_stage"], name="knowledgeba_dementi_136fb3_idx"
                    ),
                ],
            },
        ),
    ]
