# Generated by Django 4.2.10 on 2026-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0002_decoderstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavior",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
