# Generated by Django 4.2.10 on 2026-04-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dose", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("interval", "Interval")],
                        max_length=20,
                    ),
                ),
                ("time_of_day", models.TimeField(blank=True, null=True)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                (
                    "interval_hours",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("anchor_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "ordering": ["time_of_day", "anchor_time", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("skipped", "Skipped"),
                            ("refused", "Refused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now=True)),
                ("medication_name_snapshot", models.CharField(max_length=200)),
                ("dose_snapshot", models.CharField(max_length=120)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["medication", "scheduled_for"],
                        name="medications_medicat_0b2901_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="medicationlog",
            constraint=models.UniqueConstraint(
                fields=("medication", "scheduled_for"),
                name="unique_medication_scheduled_log",
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["user", "is_active", "name"],
                name="medications_user_id_0eaa93_idx",
            ),
        ),
    ]
